test_case.yml配置如下:
  # 前置准备
  prepare:
    - text: 准备相关事宜.........
    - text: 初始化图片存放位置
    - init_pic_save_path
    - text: 打开设备
    - open_devices
    - text: 打开摄像头，请手动调节拍摄位置
    - camera_test
  # 前置条件
  precondition:
    - text: 打开电源并调节电压到12V
    - battery_on
    - set_voltage_current: 12
    - acc_on
    - sleep: [10, 等待开机完成]
    - text: 拍摄基准图片的亮图
    - init_template_light_pic
  # 操作步骤
  step:
    # 循环次数
    loop_time: 5
    # 循环步骤
    loop:
      - text: 调节电压
      - change_voltage： [9, 16, 0.1, 0.1]
      - text: 拍照检查工作是否正常
      - take_a_picture_and_compare_light: True
      - text: 检查是否有重启的现象
      - judge_text_in_serial
      - text: 检查是否有CAN总线丢失
      - check_can_available
      - text: 调节电压
      - change_voltage： [16, 9, 0.1, 0.1]
      - text: 拍照检查工作是否正常
      - take_a_picture_and_compare_light: True
      - text: 检查是否有重启的现象
      - judge_text_in_serial: True
      - text: 检查是否有CAN总线丢失
      - check_can_available: True
  # 结果检查
  result:
    - text: 关闭所有设备
    - close_devices
    - text: 过滤图片，后续人工检查
    - filter_saved_images